# Generated by Django 5.0.6 on 2024-07-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.FloatField(max_length=30)),
                ('vlan_tag', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Buscar',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
