# Generated by Django 5.0.6 on 2024-07-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_hosts_rename_estudiante_buscar_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='vlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('vlan_tag', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Buscar',
        ),
    ]
