# Generated by Django 5.0.6 on 2024-07-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_vlans_delete_buscar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Hosts',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='vlans',
        ),
    ]
