# Generated by Django 5.0.6 on 2024-07-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0004_delete_entregable_delete_hosts_delete_profesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('host_ip', models.FloatField()),
                ('host_vlan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_nombre', models.CharField(max_length=60)),
                ('vlan_tag', models.IntegerField()),
                ('vlan_desc', models.CharField(max_length=60)),
            ],
        ),
    ]
