# Generated by Django 5.0.6 on 2024-07-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposables', models.CharField(max_length=60)),
                ('proyecto', models.CharField(max_length=60)),
                ('contacto', models.CharField(max_length=60)),
            ],
        ),
    ]
