# Generated by Django 5.0.6 on 2024-07-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host_ip',
            field=models.IntegerField(),
        ),
    ]
