# Generated by Django 5.0.6 on 2024-07-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_alter_hosts_host_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host_ip',
            field=models.CharField(max_length=18),
        ),
    ]
